spring.application.name=clinica-api

# banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5433/clinica_db
spring.datasource.username=admin
spring.datasource.password=admin

# jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
